service: sls-example

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x

functions:
  hello:
    handler: src/index.user
    # disini ko dicky
    events:
     - http:
         path: /
         method: any